### PR TITLE
Fix mismatched API version in ProjectService.create()

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Fixes [bug 2646 in origin-web-console](https://github.com/openshift/origin-web-console/issues/2646).

@dtaylor113 @spadgett

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
Yup, updating now, my `git add` was done in `/src`, wups

**Comment by benjaminapetersen** [comment]
all better i think.

**Comment by spadgett** [comment]
OK to merge when travis passes

**Comment by benjaminapetersen** [comment]
```
DEBUG [launcher]: Process Chrome exited with code 0
ERROR [launcher]: Cannot start Chrome
```
hmm.

**Comment by spadgett** [comment]
closing and reopening to kick travis

**Comment by benjaminapetersen** [comment]
Will that fix this one?  Was fishing around on chrome not starting in travis.  I'll watch.

**Comment by benjaminapetersen** [comment]
twice, same prob.

**Comment by benjaminapetersen** [comment]
Neat. Travis broke.

**Comment by benjaminapetersen** [comment]
```
// line 440
$ export CHROME_SOURCE_URL=http://dl.google.com/dl/linux/direct/google-chrome-stable_current_amd64.deb
Installing Google Chrome stable
0.52s$ wget --no-verbose -O /tmp/$(basename $CHROME_SOURCE_URL) $CHROME_SOURCE_URL
2018-01-09 21:47:41 URL:http://dl.google.com/dl/linux/direct/google-chrome-stable_current_amd64.deb [49565326/49565326] -> "/tmp/google-chrome-stable_current_amd64.deb" [1]
(Reading database ... 72205 files and directories currently installed.)
Preparing to unpack .../google-chrome-stable_current_amd64.deb ...
Unpacking google-chrome-stable (63.0.3239.132-1) over (62.0.3202.94-1) ...
Setting up google-chrome-stable (63.0.3239.132-1) ...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
$ export PATH=./node_modules/.bin:$PATH
//
// 547
INFO [karma]: Karma v0.12.23 server started at http://localhost:8443/
INFO [launcher]: Starting browser Chrome
DEBUG [temp-dir]: Creating temp dir at /tmp/karma-62522642
DEBUG [launcher]: google-chrome --user-data-dir=/tmp/karma-62522642 --no-default-browser-check --no-first-run --disable-default-apps --disable-popup-blocking --disable-translate --disable-background-timer-throttling --disable-renderer-backgrounding --disable-device-discovery-notifications http://localhost:8443/?id=62522642
//
// 700
DEBUG [launcher]: Process Chrome exited with code 0
ERROR [launcher]: Cannot start Chrome
// repeat & fail
```

**Comment by spadgett** [comment]
Trying Travis one more time...

**Comment by benjaminapetersen** [comment]
Nice, legit run this time with an actual fail,  fixing quick and will push.
Travis was reporting errors [on the status page](https://www.traviscistatus.com/) last night. Wasnt clear if they were causing our problems, but all green today.

**Comment by benjaminapetersen** [comment]
Perfect, Travis passed this time.

**Pull request merged**
