### PR TITLE
Incorporate slide in/out animation for toast notifications

### PR DESCRIPTION
**Pull request by sg00dwin**
- multiple toasts stack with 1px margin between
- multiple toasts have matching widths
- moved top alignment beneath top thin bar

screen shot 2017-05-08 at 2 26 12 pm
screen shot 2017-05-08 at 2 08 29 pm

### CODE REVIEW

**Comment by spadgett** [comment]
@sg00dwin 1px might be a little tight?

@serenamarie125 Wanted to get your input on this change. This is what @sg00dwin is addressing. The different widths look odd and the background page content visible between the alerts is distracting to me.

screen shot 2017-05-05 at 2 20 18 pm

cc @jwforres @rhamilto

**Comment by spadgett** [comment]
cc @jeff-phillips-18

**Comment by cshinn** [comment]
So existing toasts will lengthen to match the size of the largest one? There isn't necessarily anything wrong with that, but it may lead to a large toast wall if there are several short ones and a long message. Is there a maximum width for these toasts?

**Comment by serenamarie125** [comment]
I agree that the spacing between toasts is way too much, but i think that the proposed 1px is too little.  I would suggest somewhere between 2 - 5 px between them @beanh66.  We could do a mockup, or if you guys can try it quickly and add screenies that would work as well.  Let us know! @spadgett @sg00dwin

**Comment by spadgett** [comment]
@cshinn I believe they're a fixed width, @sg00dwin can you confirm?

**Comment by spadgett** [comment]
@serenamarie125 Thanks! We'll get some screenshots.

We could contribute the animation back upstream, although currently it is specific to an angular implementation using `ng-repeat`

**Comment by spadgett** [comment]
@serenamarie125 @beanh66 

5px margin:

openshift web console 2017-05-10 10-42-45

2px margin:

openshift web console 2017-05-10 10-43-41

Let me know if you want 3 or 4 px

**Comment by spadgett** [comment]
I found a style in origin-web-console for inline alerts that unintentionally makes the toast margin wider than it should be (as in my first screenshot above of the problem). Patternfly defaults appear to be 14px, which looks like:

openshift web console 2017-05-10 10-46-23

**Comment by beanh66** [comment]
@spadgett Thanks for sharing, I like 5px better than 2. @serenamarie125 thoughts?

**Comment by serenamarie125** [comment]
@spadgett thanks!  I'd move ahead with 5px.  In the meantime, I'll create an issue in PF to see if they can fix it in the interim.  Once that occurs, we should go back to PF.

**Comment by sg00dwin** [comment]
@cshinn @spadgett PatternFly sets a max-width on toasts when the browsers is > 768px

**Comment by serenamarie125** [comment]
fyi @spadgett https://github.com/patternfly/patternfly/issues/642

**Comment by sg00dwin** [comment]
@spadgett updated pr to 5px `margin-bottom`

screen shot 2017-05-10 at 1 16 55 pm

**Pull request merged**
