### PR TITLE
Update npm dependencies to match origin-web-console repo

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Per earlier conversation with @jwforres, this should solve the 3 items we listed.

In addition:
- new dist generated since this bumps our `uglify` plugin
- had to eliminate the `space_colon` option from the `Gruntfile` as it is no longer supported & `grunt build` failed 
- note: our minify JS for `console` and `common` are a bit different in the `Gruntfile` due to `usemin`, but the options match now.
- `jasmine-core` must now be explicitly declared

### CODE REVIEW

**Comment by spadgett** [comment]
It looks like `npm install` failed in travis. @benjaminapetersen can you take a look?

**Comment by benjaminapetersen** [comment]
yup checking it out

**Comment by benjaminapetersen** [comment]
Bumped nodejs to 6 in travis to match console, tests now pass.

**Comment by spadgett** [comment]
Hm, `grunt build` failing for me now because it can't launch Chrome :(

**Pull request merged**
