### PR TITLE
[WIP] Travis isnt starting Chrome

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Related to #276 
Not a real PR, just tinkering with Travis.

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
Chrome `stable` and `beta` both failing to start.

**Comment by dtaylor113** [comment]
In `.travis.yaml` bumping `sleep` to `10` seems to have gotten past the Travis failure.  Going to try again without the change just to verify.

**Comment by dtaylor113** [comment]
Hmm...reverted back to chrome stable without the increase in sleep time and Travis passed.

**Comment by benjaminapetersen** [comment]
Travis was reporting errors [on the status page](https://www.traviscistatus.com/) & [twitter](https://twitter.com/traviscistatus?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor)/[twitter](https://twitter.com/travisci?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor) last night.  There was issues with their NAT layer, and then some updates related to Spectre and Meltdown... so I'm betting they just blew some things up and had to put it all back together 😄

**Comment by benjaminapetersen** [comment]
Travis is running, closing this take PR

**Pull request closed without merging**
