### PR TITLE
Update jquery (3.2.1), lodash (4.17.4), and patternfly (3.25.1). Bumped Version

### PR DESCRIPTION
**Pull request by dtaylor113**
This PR updates the following dependencies:

Dependency | Version & Changes
-- | -- |
patternfly | 3.25.1
jQuery | ~2.1.4 => 3.2.1
lodash | ~3.10.1 => 4.17.4 <br>_The following changes were made:_ <br>_.indexBy => _.keyBy <br>_.pick(object,func) ⇒  _.pickBy(object,func) <br> _.contains => _.includes <br> _.trunc => _.truncate <br> _.uniq => _.uniqBy

These match the dependencies used in patternfly and angular-patternfly.

### CODE REVIEW

**Comment by spadgett** [comment]
cc @jwforres

**Comment by spadgett** [comment]
@dtaylor113 We're going to have to look at the _.sort* functions we use as well. I believe they've changed in lodash 4.

**Comment by spadgett** [comment]
https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings

https://jquery.com/upgrade-guide/3.0/

**Comment by dtaylor113** [comment]
> @dtaylor113 We're going to have to look at the _.sort* functions we use as well. I believe they've changed in lodash 4.

@spadgett , yes, those were changed in the console [PR](https://github.com/openshift/origin-web-console/pull/1838).  I did not find any _.sort calls in common.

**Comment by spadgett** [comment]
Code changes LGTM. We should wait until the other dependency PRs are ready and approved before merging, though.

**Comment by dtaylor113** [comment]
> We should wait until the other dependency PRs are ready and approved before merging, though.

Common doesn't have any other dependency PRs.  I think the merge/release order should be common, catalog, console.  -thanks :-)

**Comment by spadgett** [comment]
Right but I don't want to merge common until they are all ready and approved because it prevents us from pulling other common fixes into either repo

**Comment by spadgett** [comment]
Log links don't correctly switch to the logs tab. It looks like our `?tab=` query parameters don't work after this update.

**Comment by spadgett** [comment]
Lodash error:

```
angular.js:14199 TypeError: _.trunc is not a function
    at buildConfig.js:234
    at apply (lodash.js:496)
    at lodash.js:10863
    at apply (lodash.js:495)
    at lodash.js:6600
    at processQueue (angular.js:16696)
    at angular.js:16712
    at Scope.$eval (angular.js:17994)
    at Scope.$digest (angular.js:17808)
    at Scope.$apply (angular.js:18102)
```

**Comment by spadgett** [comment]
`DataService` still has a reference to `_.pick`

**Comment by spadgett** [comment]
Nevermind, the DataService reference should be OK

**Pull request merged**
