### PR TITLE
Bump to version 0.0.57

### PR DESCRIPTION
**Pull request by dtaylor113**

### CODE REVIEW

**Comment by spadgett** [comment]
@dtaylor113 Do you mind if we wait for #161 for @benjaminapetersen ?

**Comment by dtaylor113** [comment]
Sure, no problem.

**Comment by jeff-phillips-18** [comment]
I would expect to see a change to package-lock.json as well.

**Comment by dtaylor113** [comment]
package-lock.json updated  -thanks

**Pull request merged**
