### PR TITLE
Move ResourceGroupVersion constructor to service to eliminate global

### PR DESCRIPTION
**Pull request by benjaminapetersen**
This just wraps the constructor function in a service so we eliminate the global.

### CODE REVIEW

**Comment by spadgett** [comment]
Aren't there many instances of ResourceGroupVersion whereas a service is a singleton?

**Comment by jwforres** [comment]
yeah agree with @spadgett here, this change does not look correct

**Comment by benjaminapetersen** [comment]
Correct, you still call: 
```JavaScript 
new ResourceGroupVersion(resource, group, version);
``` 
this just puts the constructor inside a service, rather than making it a global that attaches to `window` as `window.ResourceGroupVersion`. 

Alternatively, I could move lines `3-39` inside the `.factory('APIService')`, it makes little difference to me (just eliminating the global).

**Comment by jwforres** [comment]
I see what you are saying now, and I definitely do not like defining a "Service" that isn't truly a service. I'd rather see the global moved underneath the service its being used by which is APIService, we should never be directly creating ResourceGroupVersion objects without using APIService so that we guarantee proper resolutions are happening.

**Comment by benjaminapetersen** [comment]
Ok, I may just wrapping the whole file in:

```JavaScript 
(function() {
 // code here, yay
})();
```
& that prob will do the trick w/no real changes.

**Comment by benjaminapetersen** [comment]
Updated & just wrapped in `(function() { })()`.
Also updated `kindToResouce` to change param from `kind` to `kindStr`, just to clarify it doesn't take a kind object (ran into that issue).  This is not a real change so much as self documenting.

**Pull request closed without merging**
