### PR TITLE
Added isNotificationHidden to NotificationsService

### PR DESCRIPTION
**Pull request by dtaylor113**
This is needed for https://bugzilla.redhat.com/show_bug.cgi?id=1495455#c4

`isNotificationHidden` returns `true` is user specifically cleared/hid/perm. hid the notification in the notification drawer, else returns `false`.

Also added `namespace` awareness to `isNotificationVisible` and `hideNotification` functions.

### CODE REVIEW

**Comment by spadgett** [comment]
I guess I'm unclear why this is needed. I'd rather not have to set a `namespace` property on notifications everywhere.

I was assuming the notification drawer can just include the namespace in the ID it uses for tracking whether a notification is cleared since it knows the current namespace.

**Comment by dtaylor113** [comment]
> I was assuming the notification drawer can just include the namespace in the ID

Oh, ok, that is the way I originally had it, but I thought your email indicated that you wanted the NotificationsService to take into account a `namespace`.    I'll adjust, thanks

**Comment by dtaylor113** [comment]
> I'd rather not have to set a namespace property on notifications everywhere.

Ok, fixed.

**Comment by dtaylor113** [comment]
Not needed

**Pull request closed without merging**
