### PR TITLE
Bump 0.0.76

### PR DESCRIPTION
**Pull request by benjaminapetersen**

### CODE REVIEW

**Comment by spadgett** [comment]
Closing in favor of #259

**Comment by benjaminapetersen** [comment]
Reopening just to help clarify, what is our convention going forward?  Assuming `3.9.0-alpha.0` is to match a console release, are we going to continue with `0.0.x` version bumps otherwise, or should we keep the `3.9.x` convention going forward?

Need a new bump for https://github.com/openshift/origin-web-console/pull/2550

**Comment by spadgett** [comment]
We've started using pattern `3.9.0-alpha.n`, incrementing `n` each time. It won't necessarily match a console release.

**Comment by benjaminapetersen** [comment]
Perfect, thx!

**Pull request closed without merging**
