### PR TITLE
Adopt new service catalog resource names

### PR DESCRIPTION
**Pull request by spadgett**
https://trello.com/c/y1lbFrbp

Instance -> ServiceInstance
Binding -> ServiceInstanceCredential

### CODE REVIEW

**Comment by spadgett** [comment]
Rebased

**Comment by benjaminapetersen** [comment]
Worth a conversation about a follow-on, do we want to update our internal vars & service names as well:

```JavaScript 
// now a credentialResource?
var bindingResource = {
  group: 'servicecatalog.k8s.io',
  resource: 'serviceinstancecredentials'
};		    

// CredentialService?
angular.module("openshiftCommonServices")
  .service("BindingService",

// etc.
```
Could prob make a tech debt issue

**Comment by spadgett** [comment]
Good question. We still call it "Binding" in the UI, and we will eventually make pod presets to bind to apps as well.

**Comment by benjaminapetersen** [comment]
No strong opinion then, unless we update to "Credentials" in the UI at some point.

**Pull request merged**
