### PR TITLE
Clarifying flex use case for word-break-all

### PR DESCRIPTION
**Pull request by rhamilto**

### CODE REVIEW

**Comment by sg00dwin** [comment]
@rhamilto looks good

**Comment by spadgett** [comment]
Wonder if we shouldn't add `word-break-flex` class that adds the `flex: 1 1 0%`?

**Comment by rhamilto** [comment]
> Wonder if we shouldn't add word-break-flex class that adds the flex: 1 1 0%?

What do you think, @sg00dwin?  I have mixed feelings...

**Comment by sg00dwin** [comment]
I'm not sure what having a separate `word-break-flex` gets us. Wouldn't that lead to having other cases `word-break-table`, etc.

**Comment by spadgett** [comment]
I'm OK not doing it. My only thought is that the `flex: 1 1 0%` is not at all obvious, and we'll need to comment everywhere we use it that it's required for word-break

**Comment by rhamilto** [comment]
I can haz merge?

**Pull request merged**
